services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: librarysecretpassword
      POSTGRES_DB: library
    ports:
      - '5432:5432'
    volumes:
      - pgdatalibrary:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d library']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdatalibrary:
